/// Flutter icons Moideen
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Moideen
///      fonts:
///       - asset: fonts/Moideen.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Moideen {
  Moideen._();

  static const _kFontFam = 'Moideen';
  static const Null _kFontPkg = null;

  static const IconData moideen = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
